### ISSUE TITLE
Can't load USITT ascii files.

### ISSUE THREAD

**Issue by cemkod** [claudeheintz/LXConsole4python#1]
When I try to load any ascii file, even the ones saved by the software itself, I get the following error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "lxconsole.py", line 193, in menuOpen
    p = LXCuesAsciiParser(self.cues.channels, self.cues.livecue.patch.addresses, self.cues.livecue.output)
  File "/home/jimqode/werk/lxconsole/LXCuesAsciiParser.py", line 17, in __init__
    self.cues = LXCues(channels, dimmers, interface)
TypeError: __init__() takes exactly 3 arguments (4 given)
```

**Comment by claudeheintz** [comment]
This should be now be fixed.

**Comment by cemkod** [comment]
Excuse me, my pull req didnt get merged, there are no recent commits either. how is this fixed? Everything looks exactly the same.

**Comment by claudeheintz** [comment]
I think that GitHub did not sync with my local repository as it should have. &nbsp;The fix appears online now. &nbsp;It is similar to yours except it preserves a reference to the output interface.

-Claude Heintz
&nbsp;



On Wed, 20 Sep 2017 21:38:39 +0000 (UTC), Cem Uzunoglu  wrote:
&nbsp;
Excuse me, my pull req didnt get merged, there are no recent commits either. how is this fixed? Everything looks exactly the same.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


&nbsp;
